version: '3'

services:
    python:
        build: 
            context: .
            dockerfile: ./docker/python/Dockerfile
        container_name: python_web
        ports: 
            - 5000:5000
        volumes: 
            - ./src/py:/usr/src/app