version: '3'

services:
    go_server:
        container_name: go_server
        build:
            context: .
            dockerfile: ./docker/go/Dockerfile
        ports:
            - 6060:8080
        restart: always
        volumes: 
            - ./src/go:/usr/src/app